In [1]:
import pandas as pd

part1 = pd.read_csv("../data/raw/item_properties_part1.csv")
part2 = pd.read_csv("../data/raw/item_properties_part2.csv")

In [2]:
item_properties = pd.concat(
    [part1, part2],
    ignore_index=True
)

print(item_properties.shape)

(20275902, 4)

In [3]:
categories = item_properties[
    item_properties["property"] == "categoryid"
].copy()

categories.head()

         timestamp  itemid    property value
0    1435460400000  460429  categoryid  1338
140  1432436400000  281245  categoryid  1277
151  1435460400000   35575  categoryid  1059
189  1437274800000    8313  categoryid  1147
197  1437879600000   55102  categoryid    47

In [4]:
categories = (
    categories
    .sort_values("timestamp")
    .drop_duplicates(
        subset="itemid",
        keep="last"
    )
)

In [5]:
categories = categories.rename(
    columns={
        "value": "categoryid"
    }
)

In [6]:
products = categories[
    ["itemid", "categoryid"]
].copy()

In [7]:
products.head()

          itemid categoryid
20273908  419938       1680
20273752  321873        959
2126      388926        374
13986483  336336        598
1788      197821        342

In [8]:
products = products.sort_values("itemid")

In [9]:
products.to_csv(
    "../data/processed/products.csv",
    index=False
)

In [10]:
print(products.shape)

products.head()

products.info()

(417053, 2)
<class 'pandas.core.frame.DataFrame'>
Index: 417053 entries, 19220984 to 11066336
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   itemid      417053 non-null  int64
 1   categoryid  417053 non-null  object
dtypes: int64(1), object(1)
memory usage: 9.5+ MB